version: "3.8"

x-node-env: &node-env
    image: node:16.8.0
    user: node
    ports:
        - "4000:4000"
    volumes:
        - .:/app
        - node-16:/home/node/.npm
    working_dir: "/app"
    environment:
        TZ: "Europe/Prague"
    networks:
        - spotter-app-network

services:
    node-env:
        <<: *node-env
        tty: true
    node-app:
        <<: *node-env
        command: |
            bash -c "
                sleep 3 &&
                yarn install --frozen-lockfile &&
                yarn run-prod
            "

networks:
    spotter-app-network:
        driver: bridge

volumes:
    node-16:
        external: true
